name: Build Check

on:
  push:
    commit-ignore:
      - [skip ci]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    steps:
      - name: display cmake version
        run: cmake --version